# Generated by Django 4.2.7 on 2023-12-02 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worktime', '0002_alter_workday_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('owner', 'date')},
        ),
    ]
