# Generated by Django 4.2.7 on 2023-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0003_alter_workday_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='after_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='before_work',
            field=models.IntegerField(null=True),
        ),
    ]
